name:            "Test Action"
description:     "This is a simple test action"

inputs:
  text:
    required:    true
    description: "Just some random text"

runs:
  using:         "composite"
  steps:
    - name: "Say stuff"
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_OS:    ${{ runner.os }}
      run: echo "${GITHUB_ACTOR} on ${GITHUB_OS}"
      shell: bash

    - name: "Text out"
      env:
        THE_TEXT: ${{ inputs.text }}
      run: echo "Text ${THE_TEXT}"
      shell: bash

    - name: "ls"
      run: |
        ls
      shell: bash

    - name: "git status"
      run: |
        git status
      shell: bash
